<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>net9.0</TargetFramework> 
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Pattern Result by Gasolutions</AssemblyTitle>
    <Title>Pattern result by Gasolutions.</Title>
    <Authors>José David Galviz Muñoz</Authors>
    <Company>Gasolutions SAS</Company>
    <Description>Implementación del patrón Result.</Description>
    <Copyright>Gasolutions®</Copyright>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/jgalviz1974/Patterns.Result</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <Version>$(AssemblyVersion)</Version>
    <FileVersion>$(AssemblyVersion)</FileVersion>
	<PackageOutputPath Condition="'$(SolutionDir)' != ''">$(SolutionDir)nupkgs</PackageOutputPath>
	<PackageOutputPath Condition="'$(SolutionDir)' == ''">$(MSBuildProjectDirectory)\nupkgs</PackageOutputPath>
	<IsPackable>true</IsPackable>
	 <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

	<!-- Leer CHANGELOG.md y poblar PackageReleaseNotes antes de empaquetar -->
	<Target Name="ReadPackageReleaseNotes" BeforeTargets="GenerateNuspec;Pack">
		<ReadLinesFromFile File="$(MSBuildProjectDirectory)\CHANGELOG.md">
			<Output TaskParameter="Lines" ItemName="ReleaseNotesLines" />
		</ReadLinesFromFile>

		<PropertyGroup>
			<!-- Unir las líneas leídas en una sola propiedad separada por saltos de línea (%0A) -->
			<PackageReleaseNotes>@(ReleaseNotesLines->'%(Identity)', '%0A')</PackageReleaseNotes>
		</PropertyGroup>
	</Target>
	<ItemGroup>
	  <Compile Update="Resources\Messages.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Messages.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	
  <ItemGroup>
    <None Update="readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Messages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LogicalName>Gasolutions.Core.Patterns.Result.Resources.Messages.resources</LogicalName>
      <LastGenOutput>Messages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Messages.en.resx">
      <LogicalName>Gasolutions.Core.Patterns.Result.Resources.Messages.en.resources</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
