<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <TargetFramework>net9.0</TargetFramework> 
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>Pattern Result by Gasolutions</AssemblyTitle>
    <Title>Pattern result by Gasolutions.</Title>
    <Authors>José David Galviz Muñoz</Authors>
    <Company>Gasolutions SAS</Company>
    <Description>Implementación del patrón Result.</Description>
    <Copyright>Gasolutions®</Copyright>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AssemblyVersion>1.0.8.1</AssemblyVersion>
    <Version>$(AssemblyVersion)</Version>
    <FileVersion>$(AssemblyVersion)</FileVersion>
	<PackageOutputPath Condition="'$(SolutionDir)' != ''">$(SolutionDir)nupkgs</PackageOutputPath>
	<PackageOutputPath Condition="'$(SolutionDir)' == ''">$(MSBuildProjectDirectory)\nupkgs</PackageOutputPath>
	<IsPackable>true</IsPackable>
	 <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

	<!-- Leer CHANGELOG.md y poblar PackageReleaseNotes antes de empaquetar -->
	<Target Name="ReadPackageReleaseNotes" BeforeTargets="GenerateNuspec;Pack">
		<ReadLinesFromFile File="$(MSBuildProjectDirectory)\CHANGELOG.md">
			<Output TaskParameter="Lines" ItemName="ReleaseNotesLines" />
		</ReadLinesFromFile>

		<PropertyGroup>
			<!-- Unir las líneas leídas en una sola propiedad separada por saltos de línea (%0A) -->
			<PackageReleaseNotes>@(ReleaseNotesLines->'%(Identity)', '%0A')</PackageReleaseNotes>
		</PropertyGroup>
	</Target>
	
  <ItemGroup>
    <None Update="readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
